"""Audit of Product 2's discovery overlay (app/eligibility/overlay.py).

Writes docs/CATEGORY_AUDIT.md and docs/category_audit.csv.   Run:  python tools/category_audit.py
"""
import csv
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from app.eligibility import settings  # noqa: E402
from app.eligibility.engine import EligibilityEngine  # noqa: E402
from app.eligibility.rules_compiler import compile_master  # noqa: E402

GROUP_LABEL = {"disability": "students with disabilities", "income": "a family-income limit inside your band", "farmer": "farmer families",
               "workers": "children of specific workers (beedi/cine/mine, construction, cleaning/hazardous jobs)",
               "defence": "families of armed forces / police / railway staff / freedom fighters",
               "school": "students of specific schools (Sainik/RIMC/Government school) or cadets (NCC/NDA)",
               "orphan": "PM CARES / orphan / child-care children, widows", "bpl": "BPL families",
               "teachers": "children of school teachers", "other": "other specific groups"}

base = {r.Scheme_ID: r for r in compile_master(settings.SCHEME_MASTER_PATH, overlay=False)}
new = {r.Scheme_ID: r for r in compile_master(settings.SCHEME_MASTER_PATH, overlay=True)}
active = [new[k] for k in new if new[k].Active_Status == "ACTIVE"]

rows = []
for r in active:
    if not r.Overlay_Notes:
        continue
    b = base[r.Scheme_ID]
    rows.append({"Scheme_ID": r.Scheme_ID, "Scheme_Name": r.Scheme_Name, "Level": r.Scheme_Level,
                 "State_UT": r.Scheme_State_UT, "Department": r.Department,
                 "Master_Category": b.Category_Raw, "New_Categories": r.Categories_Allowed if r.Category_Source != "master" else "",
                 "Category_Source": r.Category_Source,
                 "Master_Gender": b.Gender_Raw, "New_Gender": r.Gender_Allowed if r.Gender_Source != "master" else "",
                 "Target_Groups": r.Target_Groups, "Region_States": r.Region_States,
                 "Overlay_Notes": r.Overlay_Notes,
                 "Needs_Review": "YES" if r.Category_Source in ("inferred-department", "master+name-conflict")
                 or "Other Economically" in r.Scheme_Name else ""})

out_csv = ROOT / "docs" / "category_audit.csv"
with open(out_csv, "w", newline="", encoding="utf-8-sig") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader()
    w.writerows(rows)

cat_src = Counter(r.Category_Source for r in active if r.Category_Source != "master")
gen = [r for r in active if r.Gender_Source != "master"]
grp = Counter(g for r in active for g in r.target_group_set)
reg = [r for r in active if r.Region_States]
not_spec = sum(1 for r in base.values() if r.Active_Status == "ACTIVE" and r.Category_Raw.lower().startswith("not specified"))
cat_by_set = Counter(r.Categories_Allowed for r in active if r.Category_Source != "master")

# ---- before / after for sample General-category students
eng_old = EligibilityEngine(list(base.values()))
eng_new = EligibilityEngine(list(new.values()))
PROFILES = [
    ("Karnataka", "X", "General", "Male", 450000),     # the profile from the live test
    ("Gujarat", "XII", "General", "Female", 250000),
    ("Tamil Nadu", "XII", "General", "Male", 300000),
    ("Maharashtra", "X", "General", "Female", 400000),
    ("Kerala", "XII", "General", "Male", 200000),
    ("Assam", "X", "General", "Male", 150000),
]


def names(res):
    return [(c["name"], c["only_for"]) for c in res["schemes"]]


ba = []
for st, cl, cat, g, inc in PROFILES:
    facts = dict(state=st, class_passed=cl, category=cat, gender=g, annual_family_income=inc)
    o = eng_old.evaluate(facts)
    n = eng_new.evaluate(facts)
    ba.append((facts, o, n))

# ---- master inconsistencies worth a look (not changed by the overlay)
odd = []
for r in active:
    nm = r.Scheme_Name.lower()
    if "balak" in nm and "balika" in nm and r.Gender_Status != "NO_REQUIREMENT":
        odd.append((r.Scheme_ID, r.Scheme_Name, f"master gender '{r.Gender_Raw}' but name says Balak/Balika (boys and girls)"))

L = []
a = L.append
a("# Category & eligibility audit - Product 2 update 1")
a("")
a("Generated by `tools/category_audit.py` from `data/MoSJE_Scholarship_Master_V3.0.xlsx`. "
  f"Full row-by-row list: `docs/category_audit.csv` ({len(rows)} rows).")
a("")
a("## What was wrong")
a("")
a(f"* {not_spec} of {len(active)} active schemes have social category **\"Not specified in verified source\"** in the master.")
a("* Eligibility Rule V3.0 treats \"not specified\" as *no restriction* (PASS), so a **General** student was shown "
  "schemes whose *name* says they are for Backward Classes / SC / OBC / minorities - e.g. the Karnataka Class 10 "
  "General boy (income 3.5-4.5 lakh) from the live test saw 8 schemes, 5 of which were not for him.")
a("* The same gap existed for gender (e.g. *AICTE Pragati* = girls only) and for schemes limited to a group "
  "(disability, farmer family, PM CARES children...).")
a("")
a("## What changed (Product 2 discovery overlay - `app/eligibility/overlay.py`)")
a("")
a("Only where the master does **not** already restrict a condition; a master restriction is never loosened.")
a("")
a(f"* **Social category restricted on {sum(cat_src.values())} schemes** - {cat_src.get('inferred-name', 0)} from the scheme name "
  f"(SC, ST, OBC, BC, MBC, SEBC, SBC, VJNT, DNT, Kapu, Developing Castes, EBC/EWS, Minority, Scheduled Caste/Tribe, "
  f"Dalit, Adivasi, tribal...), {cat_src.get('inferred-department', 0)} from a single-purpose department "
  f"(e.g. *Director, Developing Castes Welfare*), {cat_src.get('master+name-conflict', 0)} master-vs-name conflicts.")
a("  * Resulting sets: " + ", ".join(f"{k} ({v})" for k, v in cat_by_set.most_common()) + ".")
a("  * The bot has 5 categories (SC, ST, OBC, General, Minority). DNT/NT/VJNT/SBC/Nomadic groups are mapped to **OBC**; "
  "EBC / EWS / economically backward schemes to **General**.")
a(f"* **Gender restricted on {len(gen)} schemes** from the name or a curated list (e.g. AICTE Pragati, Pudhumai Penn, "
  "Nijut Moina -> Female; Tamil Pudhalvan, Nijut Babu -> Male).")
a(f"* **Target groups tagged on {sum(1 for r in active if r.Target_Groups)} schemes**: " +
  ", ".join(f"{GROUP_LABEL[k].split(' (')[0]} ({v})" for k, v in grp.most_common()) + ".")
a("  * **No group is asked in chat** (the chat is limited to 5 questions: State/UT, education level, gender, "
  "family income, social category). Disability, farmer-family and other group schemes are listed **after** the main list "
  "under \"Only for specific groups - check eligibility\", each showing *Only for: students with disabilities* etc. in its detail view. "
  "A Product 1 referral can still pass `facts.disability` (Yes -> main list, No -> hidden).")
a(f"* **Region limit on {len(reg)} Central schemes**: " + "; ".join(f"{r.Scheme_Name} -> {r.Region_States}" for r in reg) + ".")
a("")
a("## Before / after - General-category students")
a("")
a("| Profile | Before | After (main list) | After (check-eligibility section) |")
a("|---|---|---|---|")
for facts, o, n in ba:
    main = sum(1 for c in n["schemes"] if not c["only_for"])
    a(f"| {facts['state']}, Class {facts['class_passed']}, {facts['gender']}, income {facts['annual_family_income']:,} | "
      f"{o['eligible_count']} | {main} | {n['eligible_count'] - main} |")
a("")
facts, o, n = ba[0]
a("**The live-test profile (Karnataka, Class 10, General, Male, 3.5-4.5 lakh):**")
a("")
a("| Scheme | Before | After |")
a("|---|---|---|")
newmap = {c["name"]: c for c in n["schemes"]}
for nm, _ in names(o):
    r = next(x for x in active if x.Scheme_Name == nm)
    if nm in newmap:
        c = newmap[nm]
        after = "shown in *check eligibility* section - only for " + ", ".join(GROUP_LABEL[g].split(' (')[0] for g in c["only_for"]) \
            if c["only_for"] else "shown"
    else:
        why = []
        if r.Category_Source != "master":
            why.append(f"category {r.Categories_Allowed}")
        if r.Gender_Source != "master":
            why.append(f"gender {r.Gender_Allowed}")
        after = "**hidden** (" + ", ".join(why) + ")" if why else "hidden"
    a(f"| {nm} | shown | {after} |")
a("")
a("With *Disability = Yes* (referral data) AICTE Saksham moves into the main list; with *No* it disappears.")
a("")
# ---- SETU income bands (monthly) for the live-test profile
BANDS = [("Up to ₹10,000 a month (≤ ₹1.2 lakh a year)", None, 120000),
         ("₹10,001–₹30,000 a month (₹1.2–3.6 lakh a year)", 120001, 360000),
         ("Above ₹30,000 a month (> ₹3.6 lakh a year)", 360001, None)]
a("### Same profile with the chat's monthly income bands (SETU options)")
a("")
a("The chat now asks family income as SETU's monthly bands. A scheme whose yearly income ceiling falls *inside* the "
  "student's band cannot be decided, so it is shown in the *check eligibility* section (\"Only for: family income up to ₹X a year\").")
a("")
a("| Income band | Main list | Check-eligibility section | Schemes in main list |")
a("|---|---|---|---|")
for label, lo, hi in BANDS:
    f = dict(state="Karnataka", class_passed="X", category="General", gender="Male", annual_family_income=hi, income_min=lo)
    res = eng_new.evaluate(f)
    main = [c["name"] for c in res["schemes"] if not c["only_for"]]
    a(f"| {label} | {len(main)} | {res['eligible_count'] - len(main)} | {'; '.join(main) or '-'} |")
a("")
# ---- education level overlay + short display fields
lvl = Counter(r.Level_Codes for r in active if r.Level_Codes)
src = {k: Counter() for k in ("description", "eligibility", "documents", "url")}
for r in active:
    for part in (r.Short_Sources or "").split("; "):
        if "=" in part:
            k, v = part.split("=", 1)
            src[k][v] += 1
no_dept = sum(1 for r in active if not (r.Department or "").strip() or (r.Department or "").lower().startswith("not specified"))
generic = Counter(r.Short_Description for r in active if "description=programme_type" in (r.Short_Sources or ""))
a("## Education level (Update 1, feedback 5)")
a("")
a("The chat asks: Class 1–10 (school), Class 10 passed, Class 12 passed, Graduation (UG), Post Graduation (PG), Other. "
  "Rule V3.0 only knows Pre-Matric / Post-Matric, so the master's `Education_Level_Raw` text is mapped to level codes "
  "(exact matches only) to keep PG-only schemes away from UG students, etc.:")
a("")
a("| Level codes | Schemes |")
a("|---|---|")
for k, v in lvl.most_common():
    a(f"| {k} | {v} |")
a(f"| (no extra limit - Rule V3.0 stage only) | {len(active) - sum(lvl.values())} |")
a("")
a("PRE -> Pre-Matric stage; X / XII -> Post-Matric; UG / PG -> Post-Matric + Higher Education. "
  "This extends Rule V3.0's Class 10/12 derivation and should be confirmed as a product decision.")
a("")
a("## Short display fields (Update 1, feedback 9)")
a("")
a("Each scheme now carries `Short_Description` (≤40 chars), `Short_Eligibility` (≤50), `Short_Documents` (≤40) and "
  "`Apply_URL`, computed when the master is compiled (`app/eligibility/display.py`, cut at a word boundary with \"…\"). "
  "Where the master has nothing, the bot shows **\"See official site\"**. Source of each field over the "
  f"{len(active)} active schemes:")
a("")
a("| Field | Source used (count) | Schemes with no source data |")
a("|---|---|---|")
names_src = {"benefits": "master `Benefits`", "programme_type": "master `Programme_Type` (generic, e.g. \"Scholarship\")",
             "structured": "built from category / income / stage / gender columns", "other_eligibilities": "master `Other_Eligibilities`",
             "documents_required": "master `Documents_Required`", "application_portal": "master `Application_Portal`",
             "source_url": "master `Source_URL` (fallback)", "none": "none"}
for k in ("description", "eligibility", "documents", "url"):
    used = ", ".join(f"{names_src.get(v, v)} ({n})" for v, n in src[k].most_common() if v != "none")
    miss = len(active) - sum(n for v, n in src[k].items() if v != "none")
    a(f"| {k} | {used} | {miss} |")
a(f"| department (title line) | master `Department` | {no_dept} |")
a("")
a("Most common generic descriptions: " + ", ".join(f"\"{k}\" ({v})" for k, v in generic.most_common(5)) +
  ". Only a minority of rows in the master have real `Benefits` / `Documents_Required` text "
  "(and the master's own benefit text is already cut at ~150 characters). Filling these columns in the master "
  "improves the cards automatically after `python tools/compile_master.py`.")
a("")
a("## Examples")
a("")
for sid in ("MSM-0273", "MSM-0104", "MSM-0283", "MSM-0069", "MSM-0225", "MSM-0084", "MSM-0394", "MSM-0179", "MSM-0016"):
    if sid in new:
        r = new[sid]
        a(f"* `{sid}` {r.Scheme_Name} - {r.Overlay_Notes}")
a("")
a("## Needs a human look")
a("")
a("Inferences are from names, so a reviewer should confirm these (all are `Needs_Review=YES` in the CSV):")
a("")
for row in rows:
    if row["Needs_Review"]:
        a(f"* `{row['Scheme_ID']}` {row['Scheme_Name']} -> {row['New_Categories']} ({row['Category_Source']}: {row['Department']})")
for sid, nm, why in odd:
    a(f"* `{sid}` {nm} - {why} (master value kept)")
a("* The permanent fix is to fill the category / gender / target-group columns in the scheme master; "
  "the overlay then has nothing to infer. After editing the master run `python tools/compile_master.py` and this audit.")
a("")
a("## Note on Rule V3.0")
a("")
a("The overlay is a Product 2 (discovery) refinement and is documented as such. Product 1's V3.0 engine is unchanged. "
  "`/v1/discover` with `include_audit=true` shows the extra `Target_Group_Result` column and each card's "
  "`only_for` list.")
(ROOT / "docs" / "CATEGORY_AUDIT.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"{len(rows)} schemes changed; wrote docs/CATEGORY_AUDIT.md and docs/category_audit.csv")
