"""Sample referral + outreach + results round trip, run fully locally (fake WhatsApp, temp SQLite).

python tools/round_trip_demo.py [--md docs/sample_referral_round_trip.md]
Shows exactly what a Product 1 sends and receives.
"""
import argparse
import json
import logging

from _local import DEMO_ENV, show_wa, start, wa_in

logging.disable(logging.INFO)
KEY = {"X-API-Key": "demo-key-rajat"}


def shorten(obj):
    """Trim long lists so the transcript stays readable."""
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if k == "suggested_schemes" and isinstance(v, list) and len(v) > 3:
                out[k] = [shorten(x) for x in v[:3]] + [f"... {len(v) - 3} more"]
            elif k == "template_text" and v and len(v) > 80:
                out[k] = v[:80] + "…"
            else:
                out[k] = shorten(v)
        return out
    if isinstance(obj, list):
        return [shorten(x) for x in obj]
    return obj


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--md")
    args = ap.parse_args()
    c, fake = start()
    md = ["# Sample round trip: Product 1 → Product 2 → Product 1",
          "",
          "Generated by `python tools/round_trip_demo.py` against a local in-process server with a fake WhatsApp API "
          "and a temporary SQLite database. The API key `demo-key-rajat` belongs to source system `p1-rajat` "
          "(`P2_API_KEYS=p1-rajat:demo-key-rajat,...`). All people and numbers are synthetic. "
          "Timestamps are UTC (`Z`).", ""]

    def call(title, method, path, body=None, headers=KEY, note=None, **kw):
        r = c.request(method, path, json=body, headers=headers, **kw)
        md.append(f"## {title}\n")
        if note:
            md.append(note + "\n")
        md.append(f"```http\n{method} {path}\nX-API-Key: {headers.get('X-API-Key', '(none)')}\n```\n")
        if body is not None:
            md.append("Request body:\n\n```json\n" + json.dumps(body, indent=2, ensure_ascii=False) + "\n```\n")
        md.append(f"Response `{r.status_code}`:\n\n```json\n" + json.dumps(shorten(r.json()), indent=2, ensure_ascii=False) + "\n```\n")
        return r.json()

    call("1. Register a callback URL (optional)", "PUT", "/v1/source-systems/me",
         {"callback_url": "https://p1-rajat.example.org/p2/callback", "callback_secret": "a-long-shared-secret-123"})
    call("2. Push referrals (students to reach)", "POST", "/v1/referrals", {"referrals": [
        {"external_ref": "P1-STU-0001", "mobile": "9876500001", "name": "Aarav Sharma", "state": "Rajasthan",
         "class_passed": "X", "category": "SC", "gender": "Male", "annual_family_income": 180000, "reason": "PROBABLE",
         "language": "en"},
        {"external_ref": "P1-STU-0002", "mobile": "9876500002", "name": "Priya Meena", "state": "Rajasthan",
         "class_passed": "XII", "reason": "UNLINKED"},
        {"external_ref": "P1-STU-0003", "mobile": "12345", "name": "Bad Number"}]})
    om = call("3. Register the outreach message and get trackable links", "POST", "/v1/outreach-messages",
              {"message_id": "2026-10-01-probable-wave1", "campaign": "PROBABLE discovery – Rajasthan – wave 1",
               "channel": "sms", "template_version": "discovery_invite_sms_v1",
               "template_text": "Namaste {{name}}, find scholarships you can explore: {{link}} Reply STOP to opt out.",
               "sent_at": "2026-10-01T09:30:00+05:30", "recipients": ["P1-STU-0001", "P1-STU-0002"]},
              note="Product 1 puts each recipient's `whatsapp_link` (or `web_link`) into the SMS/WhatsApp/email it sends. "
                   "In this demo WHATSAPP_DISPLAY_NUMBER=15550001234 and PUBLIC_BASE_URL=https://mosje-p2-api.onrender.com "
                   "(placeholders). Without a known WhatsApp number `whatsapp_link` is null.")
    rec1 = om["recipients"][0]

    md.append("## 4. Aarav taps his WhatsApp link and chats\n")
    md.append("The first message is the pre-filled text from the link; the code attributes the session to the outreach "
              "message and to recipient P1-STU-0001.\n")
    i = 0
    for text in [rec1["whatsapp_text"], "1", "1"]:
        i += 1
        before = len(fake.sent)
        c.post("/whatsapp/webhook", json=wa_in("919876500001", text, f"wamid.RT{i}"))
        md.append(f"**👤 Aarav:** {text}\n")
        for m in fake.sent[before:]:
            md.append("**🤖 Bot:**\n\n```text\n" + show_wa(m) + "\n```\n")

    rec2 = om["recipients"][1]
    from urllib.parse import parse_qs, urlparse
    q = {k: v[0] for k, v in parse_qs(urlparse(rec2["web_link"]).query).items()}
    d = call("5. Priya opens her web link (companion)", "POST", "/v1/chat/sessions", {"entry": q}, headers={},
             note="The /companion page does this call itself, passing the link's URL parameters as `entry`.")
    sid, tok = d["session_id"], d["session_token"]
    for text in ["6", "1", "2", "1", "4", "1"]:
        r = c.post(f"/v1/chat/sessions/{sid}/messages", json={"text": text}, headers={"X-Session-Token": tok}).json()
    md.append(f"Priya then picks `6` (हिंदी – the language list is alphabetical by English name), `1` (Agree to the "
              f"consent text); Class XII and Rajasthan come from the referral, so only 3 questions are left: `2` (Female), "
              f"`1` (up to ₹10,000 a month), `4` (General); then `1` (Proceed on the summary). Last reply state: "
              f"`{r['reply']['state']}`, {len(r['reply']['cards'])} scheme cards shown.\n")

    call("6. Product 1 polls one referral", "GET", "/v1/referrals/P1-STU-0001")
    res = call("7. Product 1 polls all new results", "GET", "/v1/results?since=2026-01-01T00:00:00Z")
    md.append("## 8. Callback pushed to Product 1 (one per completed session)\n")
    cb = fake.callbacks[0]
    md.append(f"`POST {cb['url']}` with header `X-P2-Signature: {cb['headers'].get('x-p2-signature', '')[:24]}…`\n")
    md.append("```json\n" + json.dumps(shorten(cb["json"]), indent=2, ensure_ascii=False)[:3000] + "\n```\n")
    call("9. Outreach message statistics", "GET", "/v1/outreach-messages/2026-10-01-probable-wave1")
    md.append(f"\nNext poll: pass `since={res['next_since']}`.\n")
    out = "\n".join(md)
    if args.md:
        open(args.md, "w", encoding="utf-8").write(out)
        print("written", args.md)
    else:
        print(out)


if __name__ == "__main__":
    main()
